### PR TITLE
fix: generate manifest files per umbrella application

### PR DESCRIPTION
**Pull request by zetaron**
I was having issues when using domo in multiple apps in the context of an umbrella project.
When attempting to compiling only one of the umbrella apps it would find modules in the meta files only available in the other umbrella app, attempting to fetch it's type information but failing because the required GenServer is missing.

This is what the error looks like for me before applying this patch:
```
$ mix compile # <- build the full umbrella, this always works
$ cd apps/app_a
$ mix compile # <- build only app_a, this fails when there are manifest files containing other apps 
** (exit) exited in: GenServer.call(Domo.TypeEnsurerFactory.ResolvePlanner, {:get_types, AnamnesisApiClient.Api.V1.CreateAnamnesis.Response}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.3) lib/gen_server.ex:1019: GenServer.call/3
    (domo 1.5.2) lib/domo/type_ensurer_factory/module_inspector.ex:20: Domo.TypeEnsurerFactory.ModuleInspector.beam_types_hash/1
    (domo 1.5.2) lib/domo/type_ensurer_factory/dependency_resolver.ex:130: anonymous fn/3 in Domo.TypeEnsurerFactory.DependencyResolver.remove_modules_with_unloadable_types/2
    (stdlib 3.17.1) maps.erl:410: :maps.fold_1/3
    (domo 1.5.2) lib/domo/type_ensurer_factory/dependency_resolver.ex:96: Domo.TypeEnsurerFactory.DependencyResolver.maybe_cleanup_deps/4
    (domo 1.5.2) lib/domo/type_ensurer_factory/dependency_resolver.ex:17: Domo.TypeEnsurerFactory.DependencyResolver.maybe_recompile_depending_structs/3
    (domo 1.5.2) lib/domo/type_ensurer_factory.ex:363: Domo.TypeEnsurerFactory.recompile_depending_structs/4
    (domo 1.5.2) lib/mix/tasks.compile.domo_compiler.ex:93: Mix.Tasks.Compile.DomoCompiler.build_ensurer_modules/2
```

The idea is to split the manifest files seperate per mix application and therefore avoid the conflicts.
This might be a crude solution, since I don't know the inner workings of this library.
It was merely the first thing I tried and it solves the issue.

### CODE REVIEW

**Comment by zetaron** [comment]
Hey @IvanRublev, I see you got an eye on this ;) 
is there anything I can help you with?
If you want I'm on MESZ Time, and would be available to meet on the elixir slack #domo.

**Comment by IvanRublev** [comment]
Hey,
Thanks for your PR. It'd be good to support independent umbrella app compilation! Let's see what I can do this week. 
It'd be a time saver if you can attach an example project illustrating the issue.

**Comment by IvanRublev** [comment]
Ok. I made a small example, and see the problem manifests now. One interesting part is types that are forced to be any(). You can run `mix compile —verbose` to see them. Currently ensurers for these are compiled in the first application and included in other apps through it. It‘d be good to share their beams, f.e. through the Domo lib‘s folder. Let‘s see what I can do.

**Comment by IvanRublev** [comment]
Hey @zetaron I’m preparing the release inspired by the idea of proposed solution! I’m going with a Elixir function returning the manifest folder per app.
The code is already in master at https://github.com/IvanRublev/Domo/tree/v1.5.3 It’d be good to know if it works for your project.

**Comment by zetaron** [comment]
Hey @IvanRublev,

I've tried the current master branch with my project and it works :)
I love how it is finally just a small change that was needed for this to work.

Thanks for making it happen so quick 👍

**Comment by IvanRublev** [comment]
The updated version [1.5.3](https://hex.pm/packages/domo/1.5.3) fixing the bug is available on hex.pm

**Pull request closed without merging**
